// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWaz6yo3dZfJiyHvo7ha2R8pU_LOjZ__M',
    appId: '1:710050778221:web:609a7a0dee926a15acc364',
    messagingSenderId: '710050778221',
    projectId: 'word-champ',
    authDomain: 'word-champ.firebaseapp.com',
    storageBucket: 'word-champ.appspot.com',
    measurementId: 'G-S53Z7F4YF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8zgjnVg9gfsnpa_sBeCDVn0KuxDGAOnc',
    appId: '1:710050778221:android:beeef2780e7d10a3acc364',
    messagingSenderId: '710050778221',
    projectId: 'word-champ',
    storageBucket: 'word-champ.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3dumHWVBLd9dGD4F2VWSK2okLoIVqk70',
    appId: '1:710050778221:ios:d3608252ac284da3acc364',
    messagingSenderId: '710050778221',
    projectId: 'word-champ',
    storageBucket: 'word-champ.appspot.com',
    iosClientId: '710050778221-hsueklfo8uufq69lcv27otjjgfa3nunb.apps.googleusercontent.com',
    iosBundleId: 'com.dovudbek.wordChamp',
  );
}
